# Generated by Django 4.0.6 on 2023-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_notification', models.TextField(blank=True, null=True)),
                ('linkfire_data_id', models.BigIntegerField(blank=True, null=True)),
                ('scheduler_id', models.BigIntegerField(blank=True, null=True)),
                ('notified_emails', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('linkfire_insights_now', models.TextField(blank=True, null=True)),
                ('linkfire_insights_before', models.TextField(blank=True, null=True)),
                ('notification_data', models.TextField(blank=True, null=True)),
                ('viewed', models.CharField(blank=True, max_length=45, null=True)),
                ('viewed_by', models.CharField(blank=True, max_length=95, null=True)),
                ('email_sent', models.CharField(blank=True, max_length=45, null=True)),
                ('email_log_output', models.TextField(blank=True, null=True)),
                ('notification_sent_on', models.DateTimeField(blank=True, null=True)),
                ('email_read_on', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.CharField(blank=True, max_length=45, null=True)),
                ('priority', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'notification_logs',
                'managed': True,
            },
        ),
    ]
