# Generated by Django 4.0.6 on 2023-02-27 13:08

from django.db import migrations, models


def update_boolean_field(apps, schema_editor):
    ScrapeLinkfires = apps.get_model("linkfire", "ScrapeLinkfires")
    for scrape_linkfire_obj in ScrapeLinkfires.objects.all():
        scrape_linkfire_obj.is_active = (
            True if scrape_linkfire_obj.active == "Yes" else False
        )
        scrape_linkfire_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("linkfire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ScrapeLinkfires",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_boolean_field),
    ]
