# Generated by Django 4.0.6 on 2023-02-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkfire', '0002_auto_20230228_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapelinkfires',
            name='active',
        ),
    ]
