# Generated by Django 4.0.6 on 2023-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='platforms',
            field=models.CharField(blank=True, choices=[('Tiktok', 'Tiktok'), ('Instagram', 'Instagram'), ('Snapchat', 'Snapchat')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='selected_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='platforms',
            field=models.CharField(choices=[('Tiktok', 'Tiktok'), ('Instagram', 'Instagram'), ('Snapchat', 'Snapchat')], max_length=45),
        ),
    ]
