# Generated by Django 4.0.6 on 2023-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_job_budget_alter_job_platforms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='content_url',
            new_name='video_id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='thumbnail_url',
            new_name='video_status',
        ),
        migrations.AddField(
            model_name='submission',
            name='vdo_payload',
            field=models.JSONField(default=dict),
        ),
    ]
