# Generated by Django 4.0.6 on 2023-03-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_jobmilestones_milestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmilestones',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone', to='marketplace.job'),
        ),
    ]
