# Generated by Django 4.0.6 on 2023-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_jobmilestones_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmilestones',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('in_progress', 'in_progress')], default='in_progress', max_length=45, null=True),
        ),
    ]
