# Generated by Django 4.0.6 on 2023-03-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_submissionviewcount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='earning_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='payout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmilestones',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('in_progress', 'in_progress')], default='in_progress', max_length=45, null=True),
        ),
    ]
