# Generated by Django 4.0.6 on 2023-03-20 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0014_earning_earning_date_payout_payout_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobmilestones",
            name="status",
        ),
        migrations.CreateModel(
            name="MilestoneStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "completed"),
                            ("in_progress", "in_progress"),
                        ],
                        default="in_progress",
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobmilestone_milestone",
                        to="marketplace.jobmilestones",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobmilestone_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "milestone_status",
                "managed": True,
            },
        ),
    ]
