# Generated by Django 4.0.6 on 2023-03-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_spentbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonestatus',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestonestatus_submission', to='marketplace.submission'),
        ),
        migrations.AlterField(
            model_name='milestonestatus',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestonestatus_milestone', to='marketplace.jobmilestones'),
        ),
    ]
