# Generated by Django 4.0.6 on 2023-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_milestonestatus_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
