# Generated by Django 4.0.6 on 2023-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_payout_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payout_status',
            field=models.CharField(blank=True, choices=[('ready_for_payout', 'ready_for_payout'), ('paid_out', 'paid_out'), ('pending', 'pending'), ('declined', 'declined')], default='ready_for_payout', max_length=45, null=True),
        ),
    ]
