# Generated by Django 4.0.6 on 2023-04-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_alter_payout_payout_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('paypal', 'paypal'), ('card', 'card')], max_length=45)),
                ('paymentid', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'completed')], default='completed', max_length=45)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpayment_brand', to='marketplace.brandprofile')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_job', to='marketplace.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
