# Generated by Django 4.0.6 on 2023-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_jobpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='thumbnails_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='thumbnails_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
