# Generated by Django 4.0.6 on 2023-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_job_thumbnails_name_job_thumbnails_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='username',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
