# Generated by Django 4.0.6 on 2023-02-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscheduler',
            name='music_sharing',
            field=models.CharField(blank=True, default='False', max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='adscheduler',
            name='stitch_duet',
            field=models.CharField(blank=True, default='False', max_length=56, null=True),
        ),
    ]
