# Generated by Django 4.0.6 on 2023-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_adscheduler_music_sharing_adscheduler_stitch_duet'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscheduler',
            name='facebook_pages_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adscheduler',
            name='instagram_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
