# Generated by Django 4.0.6 on 2023-02-27 13:08

from django.db import migrations, models


def update_boolean_field(apps, schema_editor):
    Profile = apps.get_model("common", "Profile")
    for profile_obj in Profile.objects.all():
        profile_obj.is_active = True if profile_obj.active == "Yes" else False
        profile_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_adscheduler_facebook_pages_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="Profile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_boolean_field),
    ]
