# Generated by Django 4.0.6 on 2023-03-17 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0007_remove_schedulepresetssettings_adaccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepresets',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
