# Generated by Django 4.0.6 on 2023-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_schedulepresets_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreativeids',
            name='advantage_placement',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='adscheduler',
            name='automatic_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adscheduler',
            name='selected_placement',
            field=models.CharField(blank=True, max_length=456, null=True),
        ),
    ]
