# Generated by Django 4.0.6 on 2023-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_adcreativeids_advantage_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscheduler',
            name='accelerated_spend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adscheduler',
            name='bundle_countries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adscheduler',
            name='dayparting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adscheduler',
            name='language',
            field=models.BooleanField(default=False),
        ),
    ]
