# Generated by Django 4.0.6 on 2023-04-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_dailyadspendbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyadspendbilling',
            name='ad_account_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
