# Generated by Django 4.0.6 on 2023-04-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_dailyadspendbilling_ad_account_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyadspendgenre',
            name='account_id',
            field=models.CharField(blank=True, max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='dailyadspendgenre',
            name='ad_account_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyadspendgenre',
            name='company_uid',
            field=models.CharField(blank=True, max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='dailyadspendgenre',
            name='ad_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_ads_spend_data_ad_account', to='common.adaccount'),
        ),
    ]
