# Generated by Django 4.0.6 on 2023-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_delete_dailyadspendbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
