# Generated by Django 4.0.6 on 2023-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_parting',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
