# Generated by Django 4.0.6 on 2023-05-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_adscheduler_auto_scheduler_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_profile_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
