# Generated by Django 4.0.6 on 2023-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_profile_social_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscheduler',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
