# Generated by Django 4.0.6 on 2023-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(blank=True, max_length=450, null=True)),
                ('ios_app_id', models.CharField(blank=True, max_length=95, null=True)),
                ('android_app_url', models.CharField(blank=True, max_length=450, null=True)),
                ('icon_url', models.CharField(blank=True, max_length=450, null=True)),
                ('icon_media_id', models.CharField(blank=True, max_length=450, null=True)),
            ],
            options={
                'db_table': 'snap_apps',
                'managed': True,
            },
        ),
    ]
