# Generated by Django 4.0.6 on 2023-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('otp', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'get_latest_by': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_user',
            field=models.BooleanField(default=False),
        ),
    ]
