# Generated by Django 4.0.6 on 2023-03-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registrationotp_user_is_verified_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invite_link_expire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invite_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invite_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
