# Generated by Django 4.0.6 on 2023-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_invite_link_expire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('text_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
