# Generated by Django 4.0.6 on 2023-03-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_company_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='expire_free_trial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_free_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
