# Generated by Django 4.0.6 on 2023-03-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason_to_use_everywhereai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
