# Generated by Django 4.0.6 on 2023-03-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_reason_to_use_everywhereai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_business',
        ),
    ]
