# Generated by Django 4.0.6 on 2023-03-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
