# Generated by Django 4.0.6 on 2023-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_customer_company_customer_company_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_plan_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('interval', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
