# Generated by Django 4.0.6 on 2023-03-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
    ]
