# Generated by Django 4.0.6 on 2023-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_user_id_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expire_free_trial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_free_trial',
            field=models.BooleanField(default=True),
        ),
    ]
