# Generated by Django 4.0.6 on 2023-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
    ]
