# Generated by Django 4.0.6 on 2023-02-27 13:08

from django.db import migrations, models


def update_boolean_field(apps, schema_editor):
    SpotifyProfiles = apps.get_model("scraper", "SpotifyProfiles")
    for spotify_profile_obj in SpotifyProfiles.objects.all():
        spotify_profile_obj.is_active = (
            True if spotify_profile_obj.active == "Yes" else False
        )
        spotify_profile_obj.save()

    ScraperConnection = apps.get_model("scraper", "ScraperConnection")
    for scraper_connection_obj in ScraperConnection.objects.all():
        scraper_connection_obj.is_active = (
            True if scraper_connection_obj.active == "Yes" else False
        )
        scraper_connection_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="SpotifyProfiles",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ScraperConnection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_boolean_field),
    ]
