# Generated by Django 4.0.6 on 2023-02-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account_name', models.CharField(blank=True, max_length=45, null=True)),
                ('instagram_account_id', models.CharField(blank=True, max_length=45, null=True)),
                ('instagram_profile_pic', models.TextField(blank=True, null=True)),
                ('ad_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts_ad_account', to='common.adaccount')),
            ],
            options={
                'db_table': 'instagram_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacebookUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
                ('user_access_token', models.CharField(blank=True, max_length=450, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_users_profile', to='common.profile')),
            ],
            options={
                'db_table': 'facebook_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacebookPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_name', models.CharField(blank=True, max_length=45, null=True)),
                ('page_id', models.CharField(blank=True, max_length=45, null=True)),
                ('page_token', models.CharField(blank=True, max_length=450, null=True)),
                ('active', models.CharField(blank=True, max_length=45, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('facebook_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages_facebook_user', to='facebook.facebookusers')),
            ],
            options={
                'db_table': 'facebook_pages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacebookAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=45, null=True)),
                ('account_name', models.CharField(blank=True, max_length=45, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=450, null=True)),
                ('active', models.CharField(blank=True, max_length=45, null=True)),
                ('scraper_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_accounts_scraper_group', to='common.scrapergroup')),
            ],
            options={
                'db_table': 'facebook_accounts',
                'managed': True,
            },
        ),
    ]
