# Generated by Django 4.0.6 on 2023-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpages',
            name='room_left',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
