# Generated by Django 4.0.6 on 2023-04-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_alter_facebookpages_room_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccounts',
            name='ad_account',
        ),
        migrations.AddField(
            model_name='instagramaccounts',
            name='page_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_instagram_accounts', to='facebook.facebookpages'),
        ),
    ]
