# Generated by Django 4.0.6 on 2023-04-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_remove_instagramaccounts_ad_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccounts',
            old_name='page_id',
            new_name='facebook_page_id',
        ),
    ]
