# Generated by Django 4.0.6 on 2023-04-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_rename_page_id_instagramaccounts_facebook_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccounts',
            name='facebook_page_id',
        ),
        migrations.AddField(
            model_name='instagramaccounts',
            name='facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_account_facebookpages', to='facebook.facebookpages'),
        ),
    ]
